### ISSUE TITLE
Automatic release once a tag is pushed

### ISSUE THREAD

**Issue by alfonsodelavega** [plantuml/sjpp#3]
In a fork of this repo, I've created [this workflow](https://github.com/alfonsodelavega/sjpp/blob/main/.github/workflows/tagged-release.yml) that automatically creates a release and adds the resulting jar and license file to it.

I've basically copied the build process and used the [automatic releases action](https://github.com/marketplace/actions/automatic-releases). I've avoided re-using the existing CI workflow to just focus on the automated release problem.

You can check my fork for some tests I did before arriving at the current solution. I've created this issue so that we can have a look and polish it before I add the `.yml` file to this repo.

Any thoughs?

**Comment by alfonsodelavega** [comment]
I'm currently making some changes to reuse the build workflow, [this](https://github.com/alfonsodelavega/sjpp/blob/3c7d1e7bd076972d1e28032357c4fd7903628b62/.github/workflows/tagged-release.yml) is the workflow that works fine atm.

**Comment by alfonsodelavega** [comment]
I went down the rabbit hole of trying to reuse jobs. I should've known better when the tag reached double digits D:

Basically, to avoid copy-pasting the `gradle.yml` contents into the tag release workflow, the gradle job can be called first. The problem is that [jobs run independently](https://github.com/actions/checkout/issues/19), maybe even in different machines, so no build directory is shared. Any artifact that must be preserved for the second job to work has to be shared through upload-download actions. This might become a burden with multiple files, although [advanced expressions](https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions) are allowed.

You can have a look at the current head, and also at the [previous](https://github.com/alfonsodelavega/sjpp/blob/3c7d1e7bd076972d1e28032357c4fd7903628b62/.github/workflows/tagged-release.yml) one. For something as simple as `sjpp` maybe copy-pasting is the simplest way.

**Comment by arnaudroques** [comment]
> I went down the rabbit hole of trying to reuse jobs. I should've known better when the tag reached double digits D:
> 
> Basically, to avoid copy-pasting the `gradle.yml` contents into the tag release workflow, the gradle job can be called first. The problem is that [jobs run independently](https://github.com/actions/checkout/issues/19), maybe even in different machines, so no build directory is shared. 
> [...]
>  For something as simple as `sjpp` maybe copy-pasting is the simplest way.

Yes, we can go for the simple way and use copy-pasting.
As you said, it's fine for something as simple as `sjpp`

You can propose a PR if you wish, and I will validate it.

Thanks for your help!

**Comment by alfonsodelavega** [comment]
I just pushed the `0.0.4` tag. Seems to work!

**Comment by arnaudroques** [comment]
That's great!
Congratulation for your contribution
